### ISSUE TITLE
incident rollback with fast-rollback doesn't delete deployments in staging

### ISSUE THREAD

**Issue by erutherford** [InVisionApp/kit-deployer#86] opened 2017-07-27 01:41 UTC
When using an incident rollback, I noticed that the deploys that were deleted in production weren't deleted in staging.

To provide a comparison, `01db69651b98b608ea560a13550bdd1f9452cf0b` was the previous running deploy and `853f2d9767ef345baed013cab1a23b7db09afdb6` is what we rolled back to.
Output for a prod cluster after the rollback:

```
Cluster: walmart
Namespace: default
Replica Sets:
test-rosie-v7-deployment-853f2d9767ef345baed013cab1a23b7db09afdb6-4263302119   3         3         3         2h
Deployments:
test-rosie-v7-deployment-853f2d9767ef345baed013cab1a23b7db09afdb6   3         3         3            3           2h
```

Output for a staging cluster after the rollback:
```
Cluster: staging-multi
Namespace: default
Replica Sets:
test-rosie-v7-deployment-01db69651b98b608ea560a13550bdd1f9452cf0b-4208840786   3         3         3         20m
test-rosie-v7-deployment-853f2d9767ef345baed013cab1a23b7db09afdb6-692179512    3         3         3         3h
test-rosie-v7-deployment-89b79e04dd155395f1fc61a026e46ac5f585d0ef-2812924134   3         3         3         2h
test-rosie-v7-deployment-b40c15e18af14d4ab7d2950c06717b849746ec1a-1217253705   3         3         3         2h
Deployments:
test-rosie-v7-deployment-01db69651b98b608ea560a13550bdd1f9452cf0b   3         3         3            3           20m
test-rosie-v7-deployment-853f2d9767ef345baed013cab1a23b7db09afdb6   3         3         3            3           3h
test-rosie-v7-deployment-89b79e04dd155395f1fc61a026e46ac5f585d0ef   3         3         3            3           2h
test-rosie-v7-deployment-b40c15e18af14d4ab7d2950c06717b849746ec1a   3         3         3            3           2h
```

**Comment by erutherford** [comment] 2017-07-27 02:07
I've added this as a bug here, but after further thinking I think this may be a result of the way we handle incident rollbacks.  We currently don't rollback the code in staging, we ask the users to fix master then run through a deploy or end their deployment so in actuality this is no different than the current behavior.  I'm going to leave this ticket in place until we have a chance to discuss it during work hours.

**Comment by brianhall** [comment] 2017-07-30 23:11
I think this is a dupe of #87. Please re-open if that's not the case.

**Closed by brianhall** 2017-07-30 23:11 UTC
Labels: bug
